### ISSUE TITLE
Unclear implementation details

### ISSUE THREAD

**Issue by khanh-nguyen** [thompsy/jLTE-Simulator#2]
Hi @thompsy,
I have some questions about your simulator. Hope you don't mind helping me understand it better.
- **[calcServingSectors()](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/Simulator.java#L117)**
  In your `Simulator.java()`, you use `calcServingSectors()` to find out which UE is served by which sector based on the DL gain. This is done before executing `main.run()`. However, it's only called _once_. What if UEs move? Their positions change. Shouldn't their serving sectors must change as well?
- **[ue.calculateSignalAcrossAllRBs()](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/ue/UE.java#L121)**
  In `calculateSignalAcrossAllRBs()` from `UE.java`, for each RB, you first calculate `signal = calculateSignal(RB);`, which in turn call `signalPerRB[RB.id].accumulate(rxSignal);`. Then, you call `signalPerRB[RB.id].accumulate(signal);`. That said, on the same RB, you accumulate signal twice. Why so? Is that a bug?
- **iterations**
  In your simulation, the number of iterations is 128. Is each iteration equivalent to `1ms`? Isn't it too small to achieve any meaningful result since each LTE frame is already `10ms`? Why the number of iterations must be power of 2?
- **LTE frame configuration**
  LTE specs specify fixed number of [frame configurations](http://www.radio-electronics.com/info/cellulartelecomms/lte-long-term-evolution/lte-frame-subframe-structure.php). In each configuration, there's certain number of UL and DL subframes. How is that addressed in your simulation?

Thank you very much in advance.

**Comment by thompsy** [comment]
Hi @khanh-nguyen thanks for your questions here are a few answers.
- Regarding the calcServingSectors method the assumption for our simulations was that, since we were running for a relatively short period the UEs wouldn't have enough time to move in a way that caused them to be served by another cell, therefore there was no need to re-calculate this. If true movement was to be incorporated then the serving sectors would indeed need to be recalculated.
- I see what you mean, it does look like the signal is being accumulated twice. I expect this is a bug. Feel free to fix it and send me a pull request and I'll merge it in.
- You're correct that 1 iteration is equivalent to `1ms`. This is a pretty small value but we deemed it large enough to get useful results for our purposes. Simulating a network at this scale is a expensive operation so there is always a trade-off between how much network time you would like to simulate and how much real-world time and computing resource you have available. In terms of being a power of 2 this is due to the approach we used to generate the fading values used. I can't remember the precise details as to why this was a power of 2 but if you have a play with the [GenerateFading](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/fading/GenerateFading.java) class using different iteration values it might become clear.
- We don't address different frame configurations at all in our simulator. This wasn't a detail that we were concerned about for our purposes.

If you want to use the simulator for your own purposes feel free to add the additional features that you need and I'll merge them back in. I hope that's helpful.

**Comment by khanh-nguyen** [comment]
Thanks a lot for your response, @thompsy.
- Fair enough. So if the simulation time is longer, we just need to call **calcServingSectors()** after every **k** number of iterations, right?
- I'll make a PR to fix the bug once I have the test updated correspondingly.

Just one more thing I want to clarify. In **SimMain**, for every sector, you call [sector.determineEdgeUEs()](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/SimMain.java#L81), which essentially just iterate through each UE being served and call [ue.setEdge(false)](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/sectors/AbstractSector.java#L84). What's the point of doing so? Does it mean all the UEs are treated as edge UEs? I'm not sure I understand the motivation. 

Many thanks,

**Comment by khanh-nguyen** [comment]
Never mind, I see the `determineEdgeUEs()` is overridden by each sector class.

**Comment by thompsy** [comment]
That's correct. If the simulation time is longer you may well need to call the **calcServingSectors** method after every few iterations. I can't remember whether there is any code to actually move the UEs in the current simulator so you may also need to add that. You could add the notion of directionality to the UEs and allow them to move in a specific direction and speed.

Thanks

**Comment by khanh-nguyen** [comment]
@thompsy Sorry for so many questions. For each UE, the **downlink** signal in each of its serving sector's RB is calculated as `rxSignal = downlinkPower * scheduledPowerFactor`, where the `downlinkPower` depends on the generated fading data, and `scheduledPowerFactor` is a given factor.

I guess the same formula applied for **uplink** signal, right? 
I couldn't find out the formula to calculate **uplinkPower**. Do you mind pointing me to the (source of literature for) formula to calculate `uplinkPower` from fading data, please?
or is it safe to assume that **uplink** signal in each RB is the same as _downlink_ signal? 

Thanks,

**Comment by thompsy** [comment]
No worries @khanh-nguyen I appreciate that this is a pretty complex domain! 

The uplink signal will definitely not be the same as the downlink signal. In general the transmission power of the UE's will be significantly smaller than the transmission power of the eNodeBs. There are a few things you will need to think about in order to add uplink considerations to the simulator:
1. You will need to find out the transmission power for the UE in the uplink direction. Notice in UESectorTuple that we're calculating the downlinkGain which is then being used to calculate the txPowerPerRB. I expect the gain calculation (along with the fading data) can stay the same but you will need to determine a sensible txPower value for the UEs as this will be different than that used by the sectors. 
2. The interference calculation in the uplink direction will also need to be changed. In the downlink we calculate the interference at a given UE by essentially summing the transmission power of all the sectors that are transmitting on the RB that we're concerned with. In order to do the similar operation in the uplink direction we need to calculate the interference at a given sector on a given RB. To do this you will need to determine the transmission power of all UEs that are transmitting in the uplink direction on that RB. Depending on the number of UEs that you are simulating this will be an expensive operation since you essentially need to calculate the signal between every UE and the sector that you're interested in and you will need to do this for each sector in the simulation! 

Does that make sense?

**Comment by khanh-nguyen** [comment]
Thank you so much for your response, @thompsy. This is really helpful.
1. That makes sense. However, I saw some online sources mentioned the transmit power for eNB smaller than 50dBm (~100W) like [this one](http://4g-university.com/recent-answers/lte-rel-8-enb-transmit-power/). And [this 3GPP spec](http://www.etsi.org/deliver/etsi_ts/125100_125199/125101/06.19.00_60/ts_125101v061900p.pdf) mentions UE transmission power of 24dBm. 
   In your simulation, sector's txPower is 20000 and max is 90000. Is it measured in W? And even then, the number seems to be very big compared to what I found online. Do you mind clarifying?
2. That makes sense. And that's also one of the reason I had to scale down the number of UEs.
   
   >  you will need to determine the transmission power of all UEs that are transmitting in the uplink direction on that RB

Is there any case when 1 RB is scheduled for UL for one UE, but DL for another? Is it called cross-link interference?

BTW, just wonder if you want to try [gitter](https://gitter.im/khanh-nguyen/jLTE-Simulator) for better communication?

**Comment by thompsy** [comment]
Your welcome :-)
1. If I recall correctly the eNodeB txPower talue that we were using is actually in milliwatts so that seems roughly inline with the links you mention i.e. the default txPower is 20W with 90W being the maximum. 
2. I'm not familiar with cross-link interference to be honest so I can't help you much with that. However my understanding (which you should verify from the specifications since I didn't really deal with uplink at all) is that there are basically separate resource blocks for the uplink and downlink directions such that it would not be possible for 1 RB to be scheduled in the uplink direction for one UE and simultaneously in the downlink for another. This may depend on whether you're assuming an FDD or TDD based system but I would expect that in either case some RBs are dedicated to uplink and others to the downlink.

I signed up for Gitter but I don't expect I'll be online enough to make that any more helpful I'm afraid. I'm happy to help where I can though.

in a Frequency Division Duplexing scheme the uplink and downlink resource blocks are separate

**Comment by khanh-nguyen** [comment]
1. Gotcha. Thanks for clarifying.
2. You're right. I was studying TDD problem. Let me dig around a bit more to see how it works with TDD. But from the code, it doesn't look like your simulator is tight too FDD, correct? 

Yeah, we can just stick with this thread and skip Gitter if you feel that's more convenient.
Thanks,

**Comment by khanh-nguyen** [comment]
So, in FDD, uplink and downlink can be down at the same time but using different freq. That's why UL and DL use separate RBs as you said. 
In TDD, however, duplexing is done via time division. So, a RB can be used for both UL and DL, but at each moment, only it's only used for 1 direction. ( I bet you've already known all of this, but I restate to make things clear and, hopefully, you can correct me if my understanding is incorrect).
At the same time, a sector can send while its neighbor sector is receiving, which causes cross-link interference. 

@thompsy Now, I thought I was clear about how interference is calculated but then I got a bit confused. Hope you can help me understand it better. 
1. In your code [here](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/ue/UE.java#L174), to calculate interference on a RB, you iterate through all the tuples, if a tuple is **of different sector** and if the RB is scheduled for that sector, then interference is accumulated. 
I thought a RB can only be scheduled for 1 UE. Also, each sector has its own RBs, i.e. they don't share common RBs with each other. Is that correct? If so, how can a RB be scheduled for different tuples at the same time?
2. I really have problem wrap my head around the concept of RB. Please let me know if this is the right understanding of it. Each sector has **x** RBs (`x = 100` in your settings). They can be understood as `x` customer service representatives (CSR) waiting to serve customers (UEs). At each moment we select `y` number of customers and assign them to CSRs. Each CSR (aka. RB) can only serve 1 customer (aka. UE) at a time, but several CSRs can serve 1 customer if that customer has high demand. 
Interference occurs when neighboring CSRs talk too loud that CSRs cannot hear their customers and vice versa. 

Thanks

**Comment by thompsy** [comment]
That's correct. In FDD the uplink and downlink are separated by frequency so they can both be in use simultaneously without any problems. I'm not as familiar with TDD so I can't say for sure whether your understanding is correct but it certainly seems plausible. 

Questions 1 and 2 are related here and I'll answer them in reverse order. One thing to note is that my thesis (http://downthewire.co.uk/self-organisation-in-lte-networks-final.pdf) which was based on this simulator may help you get your head around some of these concepts, in particular chapters 1 and 2 may be helpful.
1. Resource Blocks are basically an abstraction. You can think of them as bundles of time and frequency resources. So for example in a typical scheme an RB is 0.5ms wide (aka one Slot) in the time domain and 12 sub-carriers wide in the frequency domain. So in a typically system we would have 1200 sub-carriers divided into 100 RBs. 

You are correct in saying that an RB can only be used to serve a single UE but many RBs can also be used to serve a single RB. You could imagine a sector which is only serving a single UE, in this case the sector could use all its RBs to serve that one UE. Note that the single RB per UE is only true on a per slot (i.e. in the time domain) basis. So over time the same RB could be used to serve multiple UEs but only one per slot. So you could imagine a strange system where a sector only has one RB but has 10 UEs to serve. In this case it could assign that single RB to each of the UEs in different slots so that over time they could all be served. 
1. Now how does this relate to interference? Since the RBs are basically abstractions on top of the time/frequency domains they are in a sense shared by all sectors. So imagine that we have a simple system with two sectors and 100 RBs. Each sector can use the full range of 100 RBs. However in each case the RBs map to the same physical frequency resources i.e. sub-carriers. So for the first sector RB 1 is using sub-carriers 1-12. This is also true for the second sector. The fact that both sectors can be transmitting on the same RB (sub-carriers) means that they can cause interference with each others transmissions.

A useful analogy is the human voice. It operates in the time/frequency domain too but essentially has a single RB. Imagine you're in a meeting of some kind where you're presenting something and everyone else is listening. You could think of this as you being a sector transmitting a single RB to everyone present. As long as no-one within earshot of the listeners is using the same RB (i.e. as long as no one else is talking) your listeners will hear you clearly, you will have a good Signal to Interference plus Noise ratio. However if someone else were to come in and start talking at the same time as you this will cause problems for your listeners. Because both you and this other person are transmitting on the same RB (the human voice) your listeners will be hearing both signals one of which will be considered interference. In this kind of analogy the volume of the voice can be considered analogous to the transmission power. If the other person was to whisper then the interference wouldn't be as bad as if they were to start shouting! Hopefully that's helpful. Page 27 of the thesis talks about this in more depth so you may find that helpful supplemental reading.

But back to the simulator. This is why we need to accumulate the interference from all sectors using that RB. The SINR (Signal to Interference plus Noise) is what determines the signal quality. From the perspective of a UE any transmission not from it's serving sector is interference. So any other sectors transmitting on that RB will be considered by that UE to be interference. So to calculate the total interference experienced by a UE we need to sum the signal strength of every other transmission using that RB (except the UEs serving sector). 

Does that make sense? Do have a read of the first two chapters of the thesis as they should shed further light on this for you. But feel free to ask further questions too.

**Comment by khanh-nguyen** [comment]
Excellent example. :+1: Thank you so very much.
I've read your thesis before but it's worth revisiting it now.

**Comment by khanh-nguyen** [comment]
@thompsy So I reread chapter 1 and 2. Things became much clearer. However, I notice one thing. In theory, each RB is 1 slot long (0.5ms). In each slot, eNB schedules RBs to UEs. However, in the simulator, the scheduling is running once every iteration, i.e. 1ms. Was that what you wanted? 

Also, I assume in your response above, you omitted the concept of space for simplicity. In a full picture, RB is abstraction of time, freq and space, right? 2 sectors that are far away are not supposed to have interference over each other, correct? And since you omit the space dimension, I wonder how can you guarantee to not calculate interference from far away sectors? 

Again, I must say I truly appreciate your thorough responses. Your answers have helped me a lot to understand the details of LTE.

**Comment by thompsy** [comment]
Apologies for the delay in getting back to you @khanh-nguyen, real life keeps intruding ;-)

You're correct, there may be a bit of a mis-match between the slot duration and how often the simulator is scheduling. You could easily consider each iteration of the simulator to be 1 slot (i.e. 0.5ms) rather than 1ms as it currently stands. I don't think this should make a huge difference. In our case it was a detail that we were happy to abstract away!

In terms of the space dimension this is something that the simulator does deal with as it is an important aspect of the interference calculation. The distance between an eNodeB and a UE affects the pathloss of the signal between them which itself is a component of the downlink gain. This is calculated in the UESectorTuple class in the calculateDownlinkGain method. The result of this is that the further away a sector is from a UE the less interference it contributes. So the primary sources of interference (in the downlink anyway) are those eNodeBs which are close to the UE but which are not serving it. In the uplink the other UEs will become sources of interference for the eNodeBs in a similar way.

Hope that helps clarify things.

**Comment by khanh-nguyen** [comment]
No prob. at all, @thompsy. I had a long weekend without internet so only looked at your response last night as well.
Yes, I agree the difference 0.5ms and 1ms does not really affect the simulation. I just wanted to double check to make sure I didn't misunderstand something. 
So, I have some other questions (I know it's getting long :) )
- What's the meaning of the [gamma method](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/UESectorTuple.java#L26) in **UESectorTuple**? What does it represent?
- What is the model you used to [calculate downlink gain](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/UESectorTuple.java#L114) ? Do you mind linking me to the source of literatures please?
- Is downlink gain the same as antenna gain? According to this [wiki article](http://en.wikipedia.org/wiki/Antenna_gain), antenna gain represents how well the antenna converts radio waves to electrical power. If so, aren't **downlink gain** and **uplink gain** the same? 
- When X2 is enabled, each sector sorts its RBs by SINR, then tries to reserve the ones with the worst SINR. When these requests are sent around, each eNB simply tries to [reserve these RBs](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/x2/X2Router.java#L46). What if conflict occurs, i.e. more than 1 eNB try to reserve the same RB?
- In [AbstractSector](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/sectors/AbstractSector.java), you have a private variable `loadCounter` that is accessed in [`calcAvgLoad`](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/sectors/AbstractSector.java#L156) and [`generateX2Requests`](https://github.com/thompsy/jLTE-Simulator/blob/master/src/main/java/uk/co/downthewire/jLTE/simulator/sectors/AbstractSector.java#L186) but I don't see anywhere it's updated except being initialized in the constructor. Am I missing something?

**Comment by khanh-nguyen** [comment]
@thompsy I guess you were busy but I couldn't find out any good explanation for my questions above. Hopefully, you can give me some hints when you get some time. 
- So, according to the [3GPP. TS 36.942](http://www.etsi.org/deliver/etsi_tr/136900_136999/136942/12.00.00_60/tr_136942v120000p.pdf) (ref. [6] in your thesis), which you used to compute pathloss (aka. propagation model), the formula for received power is: `RX_PWR = TX_PWR – Max (pathloss – G_TX – G_RX, MCL)`, where `G_TX` is transmitter antenna gain and `G_RX` is receiver antenna gain. This is quite different from how received power is calculated in this simulation `rxSignal = txPower * scheduledPowerFactor`.
- Also, in that spec, `gamma` is either 0.8 and 1, while you had a very big function to compute it. 

If you find some time, I'd really love to get some explanation from you.

Many thanks,

**Comment by thompsy** [comment]
Apologies for the delay again @khanh-nguyen 
- The calculation for the received power is a little more complex than outlined in the 3GPP documentation. You're correct that we don't use the Max(...), instead we just stick with the pathloss and antenna gain from the antennae. The calculation for this is in the UESectorTuple. Some of the calculations for this were taken from an previous generation of simulator developed by my commercial sponsor.
- Similarly with the gamma function, our implementation is doing a bit more than the standard 3GPP values. This was again taken from another simulator which was more concerned with these values than perhaps you need to be, but it takes into account the position of the UEs along with the height of the eNodeBs since these all play a part in the gamma calculation.

**Comment by khanh-nguyen** [comment]
Hi Andrew. I apologize for my super late response. I feel so bad that I didn't see your comment until now. The issue felt off my radar. I thought you were too busy to respond and didn't follow it after that. My email filter also put github email in a different folder. 
Anyway, thank you so much for spending time answering all my questions. Your answers are very helpful. I didn't have time to make much progress since last time but will keep up posted if I have something new. 
Many thanks.

**Comment by thompsy** [comment]
No worries @khanh-nguyen, you are welcome!
